### ISSUE TITLE
Windows MSYS POSIX environment fails symlink tests

### ISSUE THREAD

**Issue by awvwgk** [MarDiehl/stdlib_os#7]
Doing a bit of tool chain testing for this project, I noticed that MSYS GCC fails to unlink the created symlink in the test executable, while for Cygwin GCC all the tests pass. This is interesting because both MSYS and Cygwin are POSIX environments for Windows and shouldn't be too different.

Maybe this is related to point 4 mentioned in https://www.msys2.org/wiki/How-does-MSYS2-differ-from-Cygwin/:

> 4. Replacement of symlinks with copying, so that Windows programs don't trip up on these files. MSYS2 also supports creating native NTFS symlinks, but these are limited in other ways.

**Comment by arjenmarkus** [comment]
Hm, that is something to look into indeed - I am not sure how useful links
are on Windows, as they are definitely almost entirely but not quite unlike
UNIX-style links.

Op di 22 dec. 2020 om 22:19 schreef Sebastian Ehlert <
notifications@github.com>:
